#!/usr/bin/env python3

# Name: tweets.py
# Author: Robin Goyal
# Last-Modified: May 28, 2017
# Purpose: Perform sentiment analysis on a twitter users 
#          50 most recent tweets

import sys
import helpers
import os

from termcolor import colored
from analyzer import Analyzer


def main():
    
    # Check if number of command line arguments is 2
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    # Absolute paths to lists 
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # Create an Analyze object
    analyzer = Analyzer(positives, negatives)
    
    # Get list of tweets from @screen_name
    tweets = helpers.get_user_timeline(sys.argv[1], 50)
    
    # Check if the get_user_timeline function returned None instead of list of tweets
    if tweets is None:
        sys.exit("Halp: Error ocurred")
     
    # Print sentiment analysis to terminal for each tweet 
    for tweet in tweets:
        
        # Return score for each tweet
        score = analyzer.analyze(tweet)
        
        # Print appropriate score and response for each tweet with colored output
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))


if __name__ == "__main__":
    main()